"use client";

import { useState } from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import { PromptBox } from "@/components/PromptBox";
import { Loader } from "@/components/Loader";
import { CheckCircle2, CopyIcon, ExternalLinkIcon, LogOut, ArrowRight, LayoutTemplate } from "lucide-react";

export default function Home() {
  const { data: session, status } = useSession();
  
  const [appState, setAppState] = useState<"idle" | "generating" | "creating" | "success" | "error">("idle");
  const [formLink, setFormLink] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async (prompt: string) => {
    try {
      setAppState("generating");
      setErrorMessage(null);
      
      // Step 1: Generate Schema
      const schemaResponse = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      
      const schemaData = await schemaResponse.json();
      if (!schemaResponse.ok) {
        throw new Error(schemaData.error || "Failed to generate schema");
      }

      setAppState("creating");
      
      // Step 2: Create Google Form
      const createResponse = await fetch("/api/create-form", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(schemaData),
      });

      const createData = await createResponse.json();
      if (!createResponse.ok) {
        throw new Error(createData.error || "Failed to create Google Form");
      }

      setFormLink(createData.link);
      setAppState("success");
    } catch (error: any) {
      console.error(error);
      setErrorMessage(error.message || "An unexpected error occurred");
      setAppState("error");
    }
  };

  const resetState = () => {
    setAppState("idle");
    setFormLink(null);
    setErrorMessage(null);
  };

  const copyToClipboard = () => {
    if (formLink) {
      navigator.clipboard.writeText(formLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="flex flex-col min-h-[100dvh] bg-zinc-50 dark:bg-zinc-950 font-sans selection:bg-black selection:text-white dark:selection:bg-white dark:selection:text-black">
      {/* Header */}
      <header className="flex h-16 w-full items-center justify-between px-6 lg:px-12 bg-white/50 dark:bg-black/50 backdrop-blur-md border-b border-zinc-200 dark:border-zinc-800">
        <div className="flex items-center gap-3">
          <div className="flex items-center justify-center p-2 bg-black text-white rounded-lg dark:bg-white dark:text-black shadow-inner">
            <LayoutTemplate className="w-5 h-5" />
          </div>
          <span className="font-bold text-xl tracking-tight text-zinc-950 dark:text-white">Formix AI</span>
        </div>
        
        {status === "authenticated" && (
          <div className="flex items-center gap-4 animate-in fade-in zoom-in duration-300">
            <span className="text-sm font-medium text-zinc-600 dark:text-zinc-400 hidden sm:block">
              {session?.user?.email}
            </span>
            <button
              onClick={() => signOut()}
              className="inline-flex h-9 items-center justify-center gap-2 rounded-lg border border-zinc-200 bg-white px-4 text-sm font-medium transition-colors hover:bg-zinc-100 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:bg-zinc-900"
            >
              Sign Out
              <LogOut className="w-4 h-4" />
            </button>
          </div>
        )}
      </header>

      {/* Main Content */}
      <main className="flex-1 flex flex-col items-center justify-center p-6 w-full max-w-4xl mx-auto">
        {status === "loading" ? (
          <Loader text="Authenticating..." />
        ) : status === "unauthenticated" ? (
          <div className="text-center animate-in fade-in slide-in-from-bottom-6 duration-700 max-w-3xl">
            <div className="inline-flex items-center rounded-full border border-black/10 bg-black/5 px-4 py-1.5 text-sm font-medium backdrop-blur-md dark:border-white/10 dark:bg-white/10 mb-8 shadow-sm">
              ✨ The perfect form in seconds
            </div>
            <h1 className="text-5xl lg:text-7xl font-bold tracking-tight text-balance text-zinc-950 dark:text-white mb-6 leading-tight">
              Forms generated by AI, <br /> hosted by Google.
            </h1>
            <p className="max-w-2xl mx-auto text-lg lg:text-xl text-zinc-600 dark:text-zinc-400 mb-12 leading-relaxed">
              Describe the form you need in plain English. Our AI analyzes your request and immediately builds a fully functional, live Google Form ready to accept responses. No dragging, no dropping.
            </p>
            <button
              onClick={() => signIn("google")}
              className="group inline-flex h-14 items-center justify-center gap-3 rounded-full bg-black px-8 text-lg font-medium text-white transition-all hover:scale-105 hover:bg-zinc-800 dark:bg-white dark:text-black dark:hover:bg-zinc-200 shadow-[0_0_40px_-10px_rgba(0,0,0,0.5)] dark:shadow-[0_0_40px_-10px_rgba(255,255,255,0.3)]"
            >
              Continue with Google
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1.5 transition-transform" />
            </button>
          </div>
        ) : (
          <div className="w-full max-w-2xl animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="mb-10 text-center">
              <h2 className="text-4xl font-bold tracking-tight mb-4 text-zinc-950 dark:text-white">Create a new form</h2>
              <p className="text-zinc-600 dark:text-zinc-400 text-lg">Describe the data you need to collect and we'll handle the rest.</p>
            </div>

            {appState === "idle" && (
              <PromptBox onSubmit={handleGenerate} isLoading={false} />
            )}

            {(appState === "generating" || appState === "creating") && (
              <div className="bg-white dark:bg-zinc-950 rounded-3xl p-12 border border-zinc-200 dark:border-zinc-800 shadow-sm flex flex-col items-center justify-center min-h-[300px]">
                <Loader 
                  text={
                    appState === "generating" 
                      ? "AI is designing your form schema..." 
                      : "Connecting to Google Forms API to build your form..."
                  } 
                />
              </div>
            )}

            {appState === "error" && (
              <div className="bg-white dark:bg-zinc-950 rounded-3xl p-8 border border-zinc-200 dark:border-zinc-800 shadow-sm flex flex-col items-center text-center">
                <div className="w-16 h-16 rounded-full bg-red-100 dark:bg-red-900/30 flex items-center justify-center mb-6 ring-8 ring-red-50 dark:ring-red-900/10">
                  <span className="text-3xl">⚠️</span>
                </div>
                <h3 className="font-semibold text-xl mb-3 text-zinc-900 dark:text-zinc-100">Generation Failed</h3>
                <p className="mb-8 text-zinc-600 dark:text-zinc-400">{errorMessage}</p>
                <button
                  onClick={resetState}
                  className="px-6 py-3 bg-zinc-900 text-white dark:bg-zinc-100 dark:text-black rounded-xl text-sm font-medium hover:bg-zinc-800 transition-colors"
                >
                  Try Again
                </button>
              </div>
            )}

            {appState === "success" && formLink && (
              <div className="bg-white dark:bg-zinc-950 rounded-3xl p-10 border border-zinc-200 dark:border-zinc-800 flex flex-col items-center text-center relative overflow-hidden shadow-xl shadow-black/5 dark:shadow-white/5">
                <div className="absolute top-0 w-full h-1.5 bg-gradient-to-r from-emerald-400 via-teal-400 to-cyan-500" />
                
                <div className="w-20 h-20 bg-emerald-50 dark:bg-emerald-500/10 rounded-full flex items-center justify-center mb-6">
                  <CheckCircle2 className="w-10 h-10 text-emerald-500" />
                </div>
                <h3 className="text-3xl font-bold tracking-tight mb-3 text-zinc-950 dark:text-white">Your form is ready!</h3>
                <p className="text-zinc-600 dark:text-zinc-400 mb-10 max-w-sm text-lg">
                  We've successfully published your form to Google Forms. It's live and ready to use.
                </p>

                <div className="flex flex-col sm:flex-row items-center gap-4 w-full px-4">
                  <a
                    href={formLink}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex flex-1 h-14 items-center justify-center gap-2 rounded-xl bg-black px-6 text-base font-medium text-white transition-all hover:scale-[1.02] hover:bg-zinc-800 dark:bg-white dark:text-black dark:hover:bg-zinc-200 w-full shadow-md shadow-black/10 dark:shadow-white/10"
                  >
                    <ExternalLinkIcon className="w-5 h-5" />
                    Open Form
                  </a>
                  
                  <button
                    onClick={copyToClipboard}
                    className="flex flex-1 h-14 items-center justify-center gap-2 rounded-xl bg-zinc-100 px-6 text-base font-medium text-zinc-900 transition-colors hover:bg-zinc-200 dark:bg-zinc-900 dark:text-white dark:hover:bg-zinc-800 w-full"
                  >
                    {copied ? (
                      <>
                        <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <CopyIcon className="w-5 h-5" />
                        Copy Link
                      </>
                    )}
                  </button>
                </div>

                <button
                  onClick={resetState}
                  className="mt-10 font-medium text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-white transition-colors border-b border-transparent hover:border-current"
                >
                  Create another form
                </button>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}
